version: 2
jobs:
  tests:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: |
            yarn

      - save_cache:
          paths:
            - ./node_modules/
          key: deps-{{ checksum "yarn.lock" }}

      - run:
          name: Fetch schema
          command: |
            mkdir schema
            yarn schema prod

      - run:
          name: Compile relay
          command: |
            yarn relay

      - run:
          name: lint
          command: |
            yarn lint

      - run:
          name: build
          command: |
            yarn build
      - run:
          name: run server
          command: |
            RELAY_ENDPOINT=https://itdagene.no/graphql/754a9fe011d12aa909bc0db296db42caaa9d28e3 yarn start
          background: true

      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:3000/
      - run:
          command: yarn test

  build-docker:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          RELEASE=${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}
          docker build -t odinuge/itdagene-webapp:$CIRCLE_BRANCH \
          --build-arg=RELEASE=$RELEASE \
          --build-arg=SENTRY_AUTH_KEY=$SENTRY_AUTH_KEY \
          --build-arg SENTRY_ORG=$SENTRY_ORG \
          --build-arg SENTRY_PROJECT=$SENTRY_PROJECT \
          --build-arg SENTRY_URL=$SENTRY_URL \
          .
      - run: docker push odinuge/itdagene-webapp:$CIRCLE_BRANCH

workflows:
  version: 2
  on_push:
    jobs:
      - tests
      - build-docker:
          requires:
            - tests
          filters:
            branches:
              only:
                - prod
